### ISSUE TITLE
Taking advantage of manual alignments

### ISSUE THREAD

**Issue by Tarotis** [lingpy/fuzzy#12]
Following the discussion in the [paper repository](https://github.com/lingpy/fuzzy/issues/3), it might be worthwhile to check if/how we can take advantage of manual alignments provided within the datasets. This might solve a good part of the confused sounds which arise due to erroneous alignments.

**Comment by LinguList** [comment]
Addressed now, but it won't lead to better results. Fix in lingrex is pending, so we do not include it in the major release.
