### ISSUE TITLE
Taking advantage of manual alignments

### ISSUE THREAD

**Issue by Tarotis** [lingpy/fuzzy#3]
@LinguList I am currently trying to get the code running for the manual alignments of the Panoan data. However, the `transform_alignment` function from lingrex overwrites the alignments in all cases. Since there is no code documentation, I struggle to solve this. Among other things, I tried manipulating the gap-argument of the function to maintain the `-`, but it did not work.

Here is an example: Cogid 242, after reducing the alignment in `panoan_prep-py`:

```
p a - n o
p a - n u
p a ɨ rⁿ o
p a - n o
```

Align=False: All gaps are removed, and the alignment is newly created in linear fashion (NOT expected for me)
Accuracy: 73%

| language      | concept   | pos   | S1    | S2    | S3    | S4       | S5   |
|:--------------|:----------|:------|:------|:------|:------|:---------|:-----|
| Amawaka       |           |       | p     | a     | n     | o        |      |
| Chakobo       |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Chaninawa     |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Kakataibo     |           |       | p     | a     | ɨ     | -        |      |
| Kapanawa      |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Katukina      |           |       | p     | a     | n     | u        |      |
| Kaxarari      |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Kaxinawa      |           |       | p     | a     | n     | u        |      |
| Korubo        |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Marinawa      |           |       | p     | a     | n     | o        |      |
| Marubo        |           |       | p     | a     | n     | o        |      |
| Matis         |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Mayoruna      |           |       | p     | a     | n     | u        |      |
| Poyanawa      |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Shanenawa     |           |       | Ø     | Ø     | Ø     | Ø        |      |
| Sharanawa     |           |       | Ø     | Ø     | Ø     | Ø        |      |
| ShipiboKonibo |           |       | p     | a     | n     | o        |      |
| Yaminawa      |           |       | p     | a     | n     | o        |      |
| Yawanawa      |           |       | p     | a     | n     | u        |      |
| Fuzzy         |           |       | p:100 | a:100 | ɨ:100 | rⁿ.o:100 |      |
| Proto-Panoan  |           |       | p     | a     | ɨ     | rⁿ       | o    |

Align=True: A new alignment is created, ignoring the manual input (as perhaps expected, using `True` as value)
Accuracy: 80%

| language      | concept   | pos   | S1    | S2          | S3     | S4    | S5   |
|:--------------|:----------|:------|:------|:------------|:-------|:------|:-----|
| Amawaka       |           |       | p     | a           | n      | o     |      |
| Chakobo       |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Chaninawa     |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Kakataibo     |           |       | p     | a           | -      | ɨ     |      |
| Kapanawa      |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Katukina      |           |       | p     | a           | n      | u     |      |
| Kaxarari      |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Kaxinawa      |           |       | p     | a           | n      | u     |      |
| Korubo        |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Marinawa      |           |       | p     | a           | n      | o     |      |
| Marubo        |           |       | p     | a           | n      | o     |      |
| Matis         |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Mayoruna      |           |       | p     | a           | n      | u     |      |
| Poyanawa      |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Shanenawa     |           |       | Ø     | Ø           | Ø      | Ø     |      |
| Sharanawa     |           |       | Ø     | Ø           | Ø      | Ø     |      |
| ShipiboKonibo |           |       | p     | a           | n      | o     |      |
| Yaminawa      |           |       | p     | a           | n      | o     |      |
| Yawanawa      |           |       | p     | a           | n      | u     |      |
| Fuzzy         |           |       | p:100 | a.ɨ:80¦a:20 | rⁿ:100 | o:100 |      |
| Proto-Panoan  |           |       | p     | a           | ɨ      | rⁿ    | o    |

The accuracy is still higher than for the other two datasets. However, I think that we lose some potential here if we don't find a way of making use of the manual work put in. How should we proceed?

**Comment by Tarotis** [comment]
For replicating the code, check the PR #4

**Comment by LinguList** [comment]
Can you please repeat what you want to do? I need to be brought back to context.

**Comment by LinguList** [comment]
@Tarotis, just understood where you are. Manual alignments don't work. The reason is: distortion leads to shifted alignments, and these are tricky to handle, so we prefer for now at least to do the alignments automatically.

**Comment by Tarotis** [comment]
Ok, then I will just set align to true and report the results accordingly. Should we make this limitation explicit when discussing the confusions?

**Comment by LinguList** [comment]
I think we CAN make it explicit in the paper. It is, however, something that comes with the method naturally. Alignments are done for one particular set of words, if you take fewer words, the alignments change. It means we need to adjust the code later to represent corrected alignments from manual alignments for subsets. I think this is worth being an open issue in lingrex, to be handled at a later state. If you want, you could file the issue there, and please add one sentence to the limitations?
